In [194]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sqlalchemy import create_engine
engine = create_engine(
    "mssql+pyodbc://localhost/SupplyChain?driver=ODBC+Driver+17+for+SQL+Server&trusted_connection=yes"
)

In [195]:
df = pd.read_csv("DataCoSupplyChainDataset.csv",encoding="latin1")

In [196]:
df.head()

,Type,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Id,Category Name,Customer City,...,Order Zipcode,Product Card Id,Product Category Id,Product Description,Product Image,Product Name,Product Price,Product Status,shipping date (DateOrders),Shipping Mode
0,DEBIT,3,4,91.250000,314.640015,Advance shipping,0,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,2/3/2018 22:56,Standard Class
1,TRANSFER,5,4,-249.089996,311.359985,Late delivery,1,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/18/2018 12:27,Standard Class
2,CASH,4,4,-247.779999,309.720001,Shipping on time,0,73,Sporting Goods,San Jose,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/17/2018 12:06,Standard Class
3,DEBIT,3,4,22.860001,304.809998,Advance shipping,0,73,Sporting Goods,Los Angeles,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/16/2018 11:45,Standard Class
4,PAYMENT,2,4,134.210007,298.250000,Advance shipping,0,73,Sporting Goods,Caguas,...,NaN,1360,73,NaN,http://images.acmesports.sports/Smart+watch,Smart watch,327.75,0,1/15/2018 11:24,Standard Class

In [197]:
df.columns

Index(['Type', 'Days for shipping (real)', 'Days for shipment (scheduled)',
       'Benefit per order', 'Sales per customer', 'Delivery Status',
       'Late_delivery_risk', 'Category Id', 'Category Name', 'Customer City',
       'Customer Country', 'Customer Email', 'Customer Fname', 'Customer Id',
       'Customer Lname', 'Customer Password', 'Customer Segment',
       'Customer State', 'Customer Street', 'Customer Zipcode',
       'Department Id', 'Department Name', 'Latitude', 'Longitude', 'Market',
       'Order City', 'Order Country', 'Order Customer Id',
       'order date (DateOrders)', 'Order Id', 'Order Item Cardprod Id',
       'Order Item Discount', 'Order Item Discount Rate', 'Order Item Id',
       'Order Item Product Price', 'Order Item Profit Ratio',
       'Order Item Quantity', 'Sales', 'Order Item Total',
       'Order Profit Per Order', 'Order Region', 'Order State', 'Order Status',
       'Order Zipcode', 'Product Card Id', 'Product Category Id',
       'Product Description', 'Product Image', 'Product Name', 'Product Price',
       'Product Status', 'shipping date (DateOrders)', 'Shipping Mode'],
      dtype='object')

In [198]:
df.shape

(180519, 53)

In [199]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 180519 entries, 0 to 180518
Data columns (total 53 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   Type                           180519 non-null  object
 1   Days for shipping (real)       180519 non-null  int64
 2   Days for shipment (scheduled)  180519 non-null  int64
 3   Benefit per order              180519 non-null  float64
 4   Sales per customer             180519 non-null  float64
 5   Delivery Status                180519 non-null  object
 6   Late_delivery_risk             180519 non-null  int64
 7   Category Id                    180519 non-null  int64
 8   Category Name                  180519 non-null  object
 9   Customer City                  180519 non-null  object
 10  Customer Country               180519 non-null  object
 11  Customer Email                 180519 non-null  object
 12  Customer Fname                 180519 non-null  object
 13  Customer Id                    180519 non-null  int64
 14  Customer Lname                 180511 non-null  object
 15  Customer Password              180519 non-null  object
 16  Customer Segment               180519 non-null  object
 17  Customer State                 180519 non-null  object
 18  Customer Street                180519 non-null  object
 19  Customer Zipcode               180516 non-null  float64
 20  Department Id                  180519 non-null  int64
 21  Department Name                180519 non-null  object
 22  Latitude                       180519 non-null  float64
 23  Longitude                      180519 non-null  float64
 24  Market                         180519 non-null  object
 25  Order City                     180519 non-null  object
 26  Order Country                  180519 non-null  object
 27  Order Customer Id              180519 non-null  int64
 28  order date (DateOrders)        180519 non-null  object
 29  Order Id                       180519 non-null  int64
 30  Order Item Cardprod Id         180519 non-null  int64
 31  Order Item Discount            180519 non-null  float64
 32  Order Item Discount Rate       180519 non-null  float64
 33  Order Item Id                  180519 non-null  int64
 34  Order Item Product Price       180519 non-null  float64
 35  Order Item Profit Ratio        180519 non-null  float64
 36  Order Item Quantity            180519 non-null  int64
 37  Sales                          180519 non-null  float64
 38  Order Item Total               180519 non-null  float64
 39  Order Profit Per Order         180519 non-null  float64
 40  Order Region                   180519 non-null  object
 41  Order State                    180519 non-null  object
 42  Order Status                   180519 non-null  object
 43  Order Zipcode                  24840 non-null   float64
 44  Product Card Id                180519 non-null  int64
 45  Product Category Id            180519 non-null  int64
 46  Product Description            0 non-null       float64
 47  Product Image                  180519 non-null  object
 48  Product Name                   180519 non-null  object
 49  Product Price                  180519 non-null  float64
 50  Product Status                 180519 non-null  int64
 51  shipping date (DateOrders)     180519 non-null  object
 52  Shipping Mode                  180519 non-null  object
dtypes: float64(15), int64(14), object(24)
memory usage: 73.0+ MB

In [200]:
df.isnull().sum().sort_values(ascending=False)

Product Description              180519
Order Zipcode                    155679
Customer Lname                        8
Customer Zipcode                      3
Days for shipment (scheduled)         0
Sales per customer                    0
Benefit per order                     0
Delivery Status                       0
Late_delivery_risk                    0
Customer City                         0
Customer Country                      0
Category Id                           0
Category Name                         0
Customer Fname                        0
Customer Email                        0
Customer Password                     0
Customer Id                           0
Customer Segment                      0
Customer State                        0
Days for shipping (real)              0
Type                                  0
Department Id                         0
Customer Street                       0
Department Name                       0
Latitude                              0
Order City                            0
Order Country                         0
Longitude                             0
Market                                0
Order Id                              0
Order Item Cardprod Id                0
Order Item Discount                   0
Order Item Discount Rate              0
Order Item Id                         0
Order Item Product Price              0
Order Customer Id                     0
order date (DateOrders)               0
Order Item Quantity                   0
Order Item Profit Ratio               0
Order Profit Per Order                0
Sales                                 0
Order Region                          0
Order State                           0
Order Status                          0
Order Item Total                      0
Product Card Id                       0
Product Category Id                   0
Product Image                         0
Product Name                          0
Product Price                         0
Product Status                        0
shipping date (DateOrders)            0
Shipping Mode                         0
dtype: int64

In [201]:
df.duplicated().sum()

np.int64(0)

In [202]:
df.describe(include="all")

,Type,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Id,Category Name,Customer City,...,Order Zipcode,Product Card Id,Product Category Id,Product Description,Product Image,Product Name,Product Price,Product Status,shipping date (DateOrders),Shipping Mode
count,180519,180519.000000,180519.000000,180519.000000,180519.000000,180519,180519.000000,180519.000000,180519,180519,...,24840.000000,180519.000000,180519.000000,0.0,180519,180519,180519.000000,180519.0,180519,180519
unique,4,NaN,NaN,NaN,NaN,4,NaN,NaN,50,563,...,NaN,NaN,NaN,NaN,118,118,NaN,NaN,63701,4
top,DEBIT,NaN,NaN,NaN,NaN,Late delivery,NaN,NaN,Cleats,Caguas,...,NaN,NaN,NaN,NaN,http://images.acmesports.sports/Perfect+Fitnes...,Perfect Fitness Perfect Rip Deck,NaN,NaN,4/17/2015 22:16,Standard Class
freq,69295,NaN,NaN,NaN,NaN,98977,NaN,NaN,24551,66770,...,NaN,NaN,NaN,NaN,24515,24515,NaN,NaN,10,107752
mean,NaN,3.497654,2.931847,21.974989,183.107609,NaN,0.548291,31.851451,NaN,NaN,...,55426.132327,692.509764,31.851451,NaN,NaN,NaN,141.232550,0.0,NaN,NaN
std,NaN,1.623722,1.374449,104.433526,120.043670,NaN,0.497664,15.640064,NaN,NaN,...,31919.279101,336.446807,15.640064,NaN,NaN,NaN,139.732492,0.0,NaN,NaN
min,NaN,0.000000,0.000000,-4274.979980,7.490000,NaN,0.000000,2.000000,NaN,NaN,...,1040.000000,19.000000,2.000000,NaN,NaN,NaN,9.990000,0.0,NaN,NaN
25%,NaN,2.000000,2.000000,7.000000,104.379997,NaN,0.000000,18.000000,NaN,NaN,...,23464.000000,403.000000,18.000000,NaN,NaN,NaN,50.000000,0.0,NaN,NaN
50%,NaN,3.000000,4.000000,31.520000,163.990005,NaN,1.000000,29.000000,NaN,NaN,...,59405.000000,627.000000,29.000000,NaN,NaN,NaN,59.990002,0.0,NaN,NaN
75%,NaN,5.000000,4.000000,64.800003,247.399994,NaN,1.000000,45.000000,NaN,NaN,...,90008.000000,1004.000000,45.000000,NaN,NaN,NaN,199.990005,0.0,NaN,NaN
max,NaN,6.000000,4.000000,911.799988,1939.989990,NaN,1.000000,76.000000,NaN,NaN,...,99301.000000,1363.000000,76.000000,NaN,NaN,NaN,1999.989990,0.0,NaN,NaN

In [203]:
drop_cols = [
    "Customer Email", "Customer Password", "Customer Fname", "Customer Lname",
    "Customer Street", "Latitude", "Longitude",
    "Product Description", "Product Image", "Product Status"
]
df = df.drop(columns=drop_cols)

In [204]:
len(df.columns)

43

In [205]:
df["order date (DateOrders)"] = pd.to_datetime(df["order date (DateOrders)"])
df["shipping date (DateOrders)"] = pd.to_datetime(df["shipping date (DateOrders)"])

In [206]:
df["shipping_delay_days"] = df["Days for shipping (real)"] - df["Days for shipment (scheduled)"]
df["is_late"] = df["shipping_delay_days"] > 0
df["profit_margin_pct"] = df["Order Profit Per Order"] / df["Sales"] * 100

df["order_month"] = df["order date (DateOrders)"].dt.month
df["order_year"] = df["order date (DateOrders)"].dt.year
df["order_weekday"] = df["order date (DateOrders)"].dt.day_name()

In [207]:
def delay_bucket(x):
    if x < 0:
        return "Early"
    elif x == 0:
        return "On-Time"
    elif x <= 2:
        return "1-2 Days Late"
    else:
        return "3+ Days Late"

df["delay_category"] = df["shipping_delay_days"].apply(delay_bucket)

In [208]:
df.head()

,Type,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Id,Category Name,Customer City,...,Product Price,shipping date (DateOrders),Shipping Mode,shipping_delay_days,is_late,profit_margin_pct,order_month,order_year,order_weekday,delay_category
0,DEBIT,3,4,91.250000,314.640015,Advance shipping,0,73,Sporting Goods,Caguas,...,327.75,2018-02-03 22:56:00,Standard Class,-1,False,27.841342,1,2018,Wednesday,Early
1,TRANSFER,5,4,-249.089996,311.359985,Late delivery,1,73,Sporting Goods,Caguas,...,327.75,2018-01-18 12:27:00,Standard Class,1,True,-75.999999,1,2018,Saturday,1-2 Days Late
2,CASH,4,4,-247.779999,309.720001,Shipping on time,0,73,Sporting Goods,San Jose,...,327.75,2018-01-17 12:06:00,Standard Class,0,False,-75.600305,1,2018,Saturday,On-Time
3,DEBIT,3,4,22.860001,304.809998,Advance shipping,0,73,Sporting Goods,Los Angeles,...,327.75,2018-01-16 11:45:00,Standard Class,-1,False,6.974829,1,2018,Saturday,Early
4,PAYMENT,2,4,134.210007,298.250000,Advance shipping,0,73,Sporting Goods,Caguas,...,327.75,2018-01-15 11:24:00,Standard Class,-2,False,40.948896,1,2018,Saturday,Early

In [209]:
float_cols = df.select_dtypes(include="float").columns
df[float_cols] = df[float_cols].round(2)

In [210]:
df.head()

,Type,Days for shipping (real),Days for shipment (scheduled),Benefit per order,Sales per customer,Delivery Status,Late_delivery_risk,Category Id,Category Name,Customer City,...,Product Price,shipping date (DateOrders),Shipping Mode,shipping_delay_days,is_late,profit_margin_pct,order_month,order_year,order_weekday,delay_category
0,DEBIT,3,4,91.25,314.64,Advance shipping,0,73,Sporting Goods,Caguas,...,327.75,2018-02-03 22:56:00,Standard Class,-1,False,27.84,1,2018,Wednesday,Early
1,TRANSFER,5,4,-249.09,311.36,Late delivery,1,73,Sporting Goods,Caguas,...,327.75,2018-01-18 12:27:00,Standard Class,1,True,-76.00,1,2018,Saturday,1-2 Days Late
2,CASH,4,4,-247.78,309.72,Shipping on time,0,73,Sporting Goods,San Jose,...,327.75,2018-01-17 12:06:00,Standard Class,0,False,-75.60,1,2018,Saturday,On-Time
3,DEBIT,3,4,22.86,304.81,Advance shipping,0,73,Sporting Goods,Los Angeles,...,327.75,2018-01-16 11:45:00,Standard Class,-1,False,6.97,1,2018,Saturday,Early
4,PAYMENT,2,4,134.21,298.25,Advance shipping,0,73,Sporting Goods,Caguas,...,327.75,2018-01-15 11:24:00,Standard Class,-2,False,40.95,1,2018,Saturday,Early

In [211]:
print(df["Product Price"].head())

0    327.75
1    327.75
2    327.75
3    327.75
4    327.75
Name: Product Price, dtype: float64

In [212]:
print(df["Product Price"].map(repr).head())

0    327.75
1    327.75
2    327.75
3    327.75
4    327.75
Name: Product Price, dtype: object

In [213]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 180519 entries, 0 to 180518
Data columns (total 50 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   Type                           180519 non-null  object
 1   Days for shipping (real)       180519 non-null  int64
 2   Days for shipment (scheduled)  180519 non-null  int64
 3   Benefit per order              180519 non-null  float64
 4   Sales per customer             180519 non-null  float64
 5   Delivery Status                180519 non-null  object
 6   Late_delivery_risk             180519 non-null  int64
 7   Category Id                    180519 non-null  int64
 8   Category Name                  180519 non-null  object
 9   Customer City                  180519 non-null  object
 10  Customer Country               180519 non-null  object
 11  Customer Id                    180519 non-null  int64
 12  Customer Segment               180519 non-null  object
 13  Customer State                 180519 non-null  object
 14  Customer Zipcode               180516 non-null  float64
 15  Department Id                  180519 non-null  int64
 16  Department Name                180519 non-null  object
 17  Market                         180519 non-null  object
 18  Order City                     180519 non-null  object
 19  Order Country                  180519 non-null  object
 20  Order Customer Id              180519 non-null  int64
 21  order date (DateOrders)        180519 non-null  datetime64[ns]
 22  Order Id                       180519 non-null  int64
 23  Order Item Cardprod Id         180519 non-null  int64
 24  Order Item Discount            180519 non-null  float64
 25  Order Item Discount Rate       180519 non-null  float64
 26  Order Item Id                  180519 non-null  int64
 27  Order Item Product Price       180519 non-null  float64
 28  Order Item Profit Ratio        180519 non-null  float64
 29  Order Item Quantity            180519 non-null  int64
 30  Sales                          180519 non-null  float64
 31  Order Item Total               180519 non-null  float64
 32  Order Profit Per Order         180519 non-null  float64
 33  Order Region                   180519 non-null  object
 34  Order State                    180519 non-null  object
 35  Order Status                   180519 non-null  object
 36  Order Zipcode                  24840 non-null   float64
 37  Product Card Id                180519 non-null  int64
 38  Product Category Id            180519 non-null  int64
 39  Product Name                   180519 non-null  object
 40  Product Price                  180519 non-null  float64
 41  shipping date (DateOrders)     180519 non-null  datetime64[ns]
 42  Shipping Mode                  180519 non-null  object
 43  shipping_delay_days            180519 non-null  int64
 44  is_late                        180519 non-null  bool
 45  profit_margin_pct              180519 non-null  float64
 46  order_month                    180519 non-null  int32
 47  order_year                     180519 non-null  int32
 48  order_weekday                  180519 non-null  object
 49  delay_category                 180519 non-null  object
dtypes: bool(1), datetime64[ns](2), float64(13), int32(2), int64(14), object(18)
memory usage: 66.3+ MB

In [214]:
category_cols = [
    "Type",
    "Delivery Status",
    "Category Name",
    "Customer Country",
    "Customer Segment",
    "Customer State",
    "Department Name",
    "Market",
    "Order Country",
    "Order Region",
    "Order State",
    "Order Status",
    "Shipping Mode",
    "order_weekday",
    "delay_category"
]

for col in category_cols:
    df[col] = df[col].astype("category")

In [215]:
int_cols = [
    "Days for shipping (real)",
    "Days for shipment (scheduled)",
    "Category Id",
    "Customer Id",
    "Department Id",
    "Order Customer Id",
    "Order Id",
    "Order Item Cardprod Id",
    "Order Item Id",
    "Order Item Quantity",
    "Product Card Id",
    "Product Category Id",
    "shipping_delay_days",
    "order_month",
    "order_year"
]

for col in int_cols:
    df[col] = df[col].astype("int32")

In [216]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 180519 entries, 0 to 180518
Data columns (total 50 columns):
 #   Column                         Non-Null Count   Dtype
---  ------                         --------------   -----
 0   Type                           180519 non-null  category
 1   Days for shipping (real)       180519 non-null  int32
 2   Days for shipment (scheduled)  180519 non-null  int32
 3   Benefit per order              180519 non-null  float64
 4   Sales per customer             180519 non-null  float64
 5   Delivery Status                180519 non-null  category
 6   Late_delivery_risk             180519 non-null  int64
 7   Category Id                    180519 non-null  int32
 8   Category Name                  180519 non-null  category
 9   Customer City                  180519 non-null  object
 10  Customer Country               180519 non-null  category
 11  Customer Id                    180519 non-null  int32
 12  Customer Segment               180519 non-null  category
 13  Customer State                 180519 non-null  category
 14  Customer Zipcode               180516 non-null  float64
 15  Department Id                  180519 non-null  int32
 16  Department Name                180519 non-null  category
 17  Market                         180519 non-null  category
 18  Order City                     180519 non-null  object
 19  Order Country                  180519 non-null  category
 20  Order Customer Id              180519 non-null  int32
 21  order date (DateOrders)        180519 non-null  datetime64[ns]
 22  Order Id                       180519 non-null  int32
 23  Order Item Cardprod Id         180519 non-null  int32
 24  Order Item Discount            180519 non-null  float64
 25  Order Item Discount Rate       180519 non-null  float64
 26  Order Item Id                  180519 non-null  int32
 27  Order Item Product Price       180519 non-null  float64
 28  Order Item Profit Ratio        180519 non-null  float64
 29  Order Item Quantity            180519 non-null  int32
 30  Sales                          180519 non-null  float64
 31  Order Item Total               180519 non-null  float64
 32  Order Profit Per Order         180519 non-null  float64
 33  Order Region                   180519 non-null  category
 34  Order State                    180519 non-null  category
 35  Order Status                   180519 non-null  category
 36  Order Zipcode                  24840 non-null   float64
 37  Product Card Id                180519 non-null  int32
 38  Product Category Id            180519 non-null  int32
 39  Product Name                   180519 non-null  object
 40  Product Price                  180519 non-null  float64
 41  shipping date (DateOrders)     180519 non-null  datetime64[ns]
 42  Shipping Mode                  180519 non-null  category
 43  shipping_delay_days            180519 non-null  int32
 44  is_late                        180519 non-null  bool
 45  profit_margin_pct              180519 non-null  float64
 46  order_month                    180519 non-null  int32
 47  order_year                     180519 non-null  int32
 48  order_weekday                  180519 non-null  category
 49  delay_category                 180519 non-null  category
dtypes: bool(1), category(15), datetime64[ns](2), float64(13), int32(15), int64(1), object(3)
memory usage: 39.6+ MB

In [217]:
dim_customer = df[[
    "Customer Id", "Customer Segment", "Customer City",
    "Customer State", "Customer Country", "Customer Zipcode"
]].drop_duplicates(subset="Customer Id").reset_index(drop=True)

In [218]:
dim_customer.head()

,Customer Id,Customer Segment,Customer City,Customer State,Customer Country,Customer Zipcode
0,20755,Consumer,Caguas,PR,Puerto Rico,725.0
1,19492,Consumer,Caguas,PR,Puerto Rico,725.0
2,19491,Consumer,San Jose,CA,EE. UU.,95125.0
3,19490,Home Office,Los Angeles,CA,EE. UU.,90027.0
4,19489,Corporate,Caguas,PR,Puerto Rico,725.0

In [219]:
dim_product = df[[
    "Product Card Id", "Product Name", "Product Category Id",
    "Category Name", "Product Price"
]].drop_duplicates(subset="Product Card Id").reset_index(drop=True)

In [220]:
print(dim_product["Product Price"].map(repr).head())

0    327.75
1     59.99
2     39.99
3      50.0
4     44.99
Name: Product Price, dtype: object

In [221]:
dim_product.head()

,Product Card Id,Product Name,Product Category Id,Category Name,Product Price
0,1360,Smart watch,73,Sporting Goods,327.75
1,365,Perfect Fitness Perfect Rip Deck,17,Cleats,59.99
2,627,Under Armour Girls' Toddler Spine Surge Runni,29,Shop By Sport,39.99
3,502,Nike Men's Dri-FIT Victory Golf Polo,24,Women's Apparel,50.00
4,278,Under Armour Men's Compression EV SL Slide,13,Electronics,44.99

In [222]:
dim_department = df[[
    "Department Id", "Department Name"
]].drop_duplicates(subset="Department Id").reset_index(drop=True)

In [223]:
dim_department.head()

   Department Id Department Name
0              2         Fitness
1              4         Apparel
2              5            Golf
3              3        Footwear
4              6        Outdoors

In [224]:
dim_shipping = df[["Shipping Mode"]].drop_duplicates().reset_index(drop=True)

dim_shipping["ShippingModeKey"] = dim_shipping.index + 1

df = df.merge(
    dim_shipping,
    on="Shipping Mode",
    how="left"
)

In [225]:
dim_shipping.head()

    Shipping Mode  ShippingModeKey
0  Standard Class                1
1     First Class                2
2    Second Class                3
3        Same Day                4

In [226]:
dim_location = df[[
    "Order Country",
    "Order State",
    "Order City",
    "Market",
    "Order Region"
]].drop_duplicates().reset_index(drop=True)

dim_location["LocationKey"] = dim_location.index + 1

df = df.merge(
    dim_location,
    on=[
        "Order Country",
        "Order State",
        "Order City",
        "Market",
        "Order Region"
    ],
    how="left"
)

In [227]:
dim_location.head()

,Order Country,Order State,Order City,Market,Order Region,LocationKey
0,Indonesia,Java Occidental,Bekasi,Pacific Asia,Southeast Asia,1
1,India,Rajastán,Bikaner,Pacific Asia,South Asia,2
2,Australia,Queensland,Townsville,Pacific Asia,Oceania,3
3,Australia,Queensland,Toowoomba,Pacific Asia,Oceania,4
4,China,Guangdong,Guangzhou,Pacific Asia,Eastern Asia,5

In [228]:
dim_date = pd.DataFrame({
    "Date": pd.date_range(
        start=df["order date (DateOrders)"].min(),
        end=df["order date (DateOrders)"].max()
    )
})

dim_date["DateKey"] = dim_date["Date"].dt.strftime("%Y%m%d").astype(int)
dim_date["Year"] = dim_date["Date"].dt.year
dim_date["Quarter"] = dim_date["Date"].dt.quarter
dim_date["Month"] = dim_date["Date"].dt.month
dim_date["MonthName"] = dim_date["Date"].dt.month_name()
dim_date["Weekday"] = dim_date["Date"].dt.day_name()
dim_date["WeekdayNumber"] = dim_date["Date"].dt.weekday
dim_date["Weekend"] = dim_date["WeekdayNumber"] >= 5

df["DateKey"] = df["order date (DateOrders)"].dt.strftime("%Y%m%d").astype(int)

In [229]:
dim_date.head()

,Date,DateKey,Year,Quarter,Month,MonthName,Weekday,WeekdayNumber,Weekend
0,2015-01-01,20150101,2015,1,1,January,Thursday,3,False
1,2015-01-02,20150102,2015,1,1,January,Friday,4,False
2,2015-01-03,20150103,2015,1,1,January,Saturday,5,True
3,2015-01-04,20150104,2015,1,1,January,Sunday,6,True
4,2015-01-05,20150105,2015,1,1,January,Monday,0,False

In [230]:
fact_orders = df[
[
    "Order Id",
    "Order Item Id",

    "Customer Id",
    "Product Card Id",
    "Department Id",

    "ShippingModeKey",
    "LocationKey",
    "DateKey",

    "shipping date (DateOrders)",

    "Days for shipping (real)",
    "Days for shipment (scheduled)",

    "shipping_delay_days",
    "is_late",
    "delay_category",

    "Late_delivery_risk",
    "Delivery Status",
    "Order Status",

    "Sales",
    "Order Item Total",
    "Order Profit Per Order",

    "Order Item Discount",
    "Order Item Discount Rate",

    "Order Item Quantity",

    "Order Item Product Price",

    "profit_margin_pct"
]
]

In [231]:
fact_orders.head()

,Order Id,Order Item Id,Customer Id,Product Card Id,Department Id,ShippingModeKey,LocationKey,DateKey,shipping date (DateOrders),Days for shipping (real),...,Delivery Status,Order Status,Sales,Order Item Total,Order Profit Per Order,Order Item Discount,Order Item Discount Rate,Order Item Quantity,Order Item Product Price,profit_margin_pct
0,77202,180517,20755,1360,2,1,1,20180131,2018-02-03 22:56:00,3,...,Advance shipping,COMPLETE,327.75,314.64,91.25,13.11,0.04,1,327.75,27.84
1,75939,179254,19492,1360,2,1,2,20180113,2018-01-18 12:27:00,5,...,Late delivery,PENDING,327.75,311.36,-249.09,16.39,0.05,1,327.75,-76.00
2,75938,179253,19491,1360,2,1,2,20180113,2018-01-17 12:06:00,4,...,Shipping on time,CLOSED,327.75,309.72,-247.78,18.03,0.06,1,327.75,-75.60
3,75937,179252,19490,1360,2,1,3,20180113,2018-01-16 11:45:00,3,...,Advance shipping,COMPLETE,327.75,304.81,22.86,22.94,0.07,1,327.75,6.97
4,75936,179251,19489,1360,2,1,3,20180113,2018-01-15 11:24:00,2,...,Advance shipping,PENDING_PAYMENT,327.75,298.25,134.21,29.50,0.09,1,327.75,40.95

In [236]:
def to_snake(col):
    return (col.lower()
               .replace(" (dateorders)", "")
               .replace(" ", "_"))

fact_orders.columns = [to_snake(c) for c in fact_orders.columns]
dim_customer.columns = [to_snake(c) for c in dim_customer.columns]
dim_product.columns = [to_snake(c) for c in dim_product.columns]
dim_department.columns = [to_snake(c) for c in dim_department.columns]
dim_shipping.columns = [to_snake(c) for c in dim_shipping.columns]
dim_location.columns = [to_snake(c) for c in dim_location.columns]

In [237]:
dim_customer.head()

,customer_id,customer_segment,customer_city,customer_state,customer_country,customer_zipcode
0,20755,Consumer,Caguas,PR,Puerto Rico,725.0
1,19492,Consumer,Caguas,PR,Puerto Rico,725.0
2,19491,Consumer,San Jose,CA,EE. UU.,95125.0
3,19490,Home Office,Los Angeles,CA,EE. UU.,90027.0
4,19489,Corporate,Caguas,PR,Puerto Rico,725.0

In [238]:
fact_orders.to_sql("fact_orders", engine, if_exists="replace", index=False)
dim_customer.to_sql("dim_customer", engine, if_exists="replace", index=False)
dim_product.to_sql("dim_product", engine, if_exists="replace", index=False)
dim_department.to_sql("dim_department", engine, if_exists="replace", index=False)
dim_shipping.to_sql("dim_shipping", engine, if_exists="replace", index=False)
dim_location.to_sql("dim_location", engine, if_exists="replace", index=False)
dim_date.to_sql("dim_date", engine, if_exists="replace", index=False)

195